### ISSUE TITLE
打包没有依赖包

### ISSUE THREAD

**Issue by hb0730** [hb0730/boot-admin#2]
在build package后生成的jar包没有依赖包

**Comment by hb0730** [comment]
官方解决方案 [goals-repackage](https://docs.spring.io/spring-boot/docs/2.5.3/maven-plugin/reference/htmlsingle/#goals-repackage) [packaging](https://docs.spring.io/spring-boot/docs/2.5.3/maven-plugin/reference/htmlsingle/#packaging)

**Comment by ljh-haha** [comment]
数据库数据在哪呀？

**Comment by hb0730** [comment]
> 数据库数据在哪呀？

doc 文件夹下
