### ISSUE TITLE
v6.3 提示程序包com.hb0730.opentelemetry.rpc不存在

### ISSUE THREAD

**Issue by armran** [hb0730/boot-admin#27]
直接拉取后，idea不报错，但运行提示：

boot-admin\commons\common-opentelemetry\opentelemetry-configuration\src\main\java\com\hb0730\opentelemetry\autoconfigure\rpc\OpenTelemetrySofaRpcAutoConfiguration.java:3:36
java: 程序包com.hb0730.opentelemetry.rpc不存在

**Comment by hb0730** [comment]
> 直接拉取后，idea不报错，但运行提示：
> 
> boot-admin\commons\common-opentelemetry\opentelemetry-configuration\src\main\java\com\hb0730\opentelemetry\autoconfigure\rpc\OpenTelemetrySofaRpcAutoConfiguration.java:3:36 java: 程序包com.hb0730.opentelemetry.rpc不存在

请先`mvn clean -DskipTests=true package`

**Comment by hb0730** [comment]
或者修改`opentelemetry-configuration/pom.xml`中的
```xml
<dependency>
    <groupId>com.hb0730</groupId>
    <artifactId>opentelemetry-rpc</artifactId>
    <version>${revision}</version>
    <optional>true</optional>
</dependency>
```
改为
```xml
<dependency>
    <groupId>com.hb0730</groupId>
    <artifactId>opentelemetry-rpc</artifactId>
    <version>${revision}</version>
</dependency>
```
删除 `<optional>true</optional>`
