### ISSUE TITLE
boot-admin和boot-admin-ui怎么配置才能正常登录？

### ISSUE THREAD

**Issue by philipf-chen** [hb0730/boot-admin#4]
前端项目和后端项目均在本地启动，
前端配置如下：
proxy: {
      '/': {
        target: 'http://localhost:8080', //目标接口域名
        secure: false, //false为http访问，true为https访问
        changeOrigin: true, //是否跨域
        pathRewrite: {
        '^/': '' //重写接口
        }
后端配置：
server:
  port: 8080
spring:
  application:
    name: boot-admin-3.0.0

Administrator/123456 登录页面弹窗显示：
Network Error
后台无任何日志输出。

**Comment by philipf-chen** [comment]
前端配置中修改为不跨域：
changeOrigin: false, //是否跨域
启动后访问：
依然是
Network Error

但是后台有日志输出了：
org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource
	at org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:189)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:140)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

**Comment by philipf-chen** [comment]
能否写一个简单的启动文档，按照步骤操作，确保能够成功登录进去。
另外，演示网站:
https://admin.hb0730.com 
使用Administrator/123456登录，也是显示Network Error

**Comment by hb0730** [comment]
演示网站是因为启用了
![image](https://user-images.githubusercontent.com/33956166/141232904-149bc66b-173a-4870-9625-3c279bc2db7b.png)
观点就可以了，

如何正常访问问题：
1. 首先正确配置前端项目[*.env](https://github.com/hb0730/boot-admin-ui/blob/v3/.env)
2. 后台项目所需的依赖如：redis,mysql等

**Comment by hb0730** [comment]
前端本地
![image](https://user-images.githubusercontent.com/33956166/141233133-28855568-c8da-48f9-b187-3f663574291c.png)

启动命令为`npm run serve `

**Comment by hb0730** [comment]
> 前端配置中修改为不跨域： changeOrigin: false, //是否跨域 启动后访问： 依然是 Network Error
> 
> 但是后台有日志输出了： org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource at org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:189) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:140) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

这是可能访问了受`spring security`保护的资源了

**Comment by philipf-chen** [comment]
> 前端本地 ![image](https://user-images.githubusercontent.com/33956166/141233133-28855568-c8da-48f9-b187-3f663574291c.png)
> 
> 启动命令为`npm run serve `

配置了env文件，终于进去了，谢谢。
如果能在Readme中加上这些指导，那就更好了。

**Comment by hb0730** [comment]
> > 前端本地 ![image](https://user-images.githubusercontent.com/33956166/141233133-28855568-c8da-48f9-b187-3f663574291c.png)
> > 启动命令为`npm run serve `
> 
> 配置了env文件，终于进去了，谢谢。 如果能在Readme中加上这些指导，那就更好了。

这个我觉着应该不需要写，因为前端项目已经根据环境去区分了只要熟悉启动过程加载什么文件就明白了

**Comment by philipf-chen** [comment]
像我，只懂得后端开发，前端知之甚少。
但我也想用大佬搞的这个项目，这就很需要指导了。
